# FOLDER_PERMISSIONS
# Opening Session Welcome to the Capturator, this is the Folder place
# -----------------------------------------------------

- !LookerFolder
  parent_id:
  id: '1'
  name: Shared
  subfolder:
  - !LookerFolder
    parent_id: '1'
    id: '8'
    name: PIN
    subfolder:
    - !LookerFolder
      parent_id: '8'
      id: '50'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '189'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '49'
      name: Utilization
      subfolder: []
      content_metadata_id: '188'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '48'
      name: Supervisory
      subfolder: []
      content_metadata_id: '187'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '47'
      name: System Admin
      subfolder: []
      content_metadata_id: '186'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '46'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '185'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '45'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '184'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '44'
      name: Outcomes
      subfolder: []
      content_metadata_id: '183'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '43'
      name: Operations
      subfolder: []
      content_metadata_id: '182'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '42'
      name: External/Grants
      subfolder: []
      content_metadata_id: '181'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '41'
      name: Executive
      subfolder: []
      content_metadata_id: '180'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '40'
      name: Clinical
      subfolder: []
      content_metadata_id: '179'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '39'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '178'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '38'
      name: Administrative
      subfolder: []
      content_metadata_id: '177'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '37'
      name: In Progress
      subfolder: []
      content_metadata_id: '176'
      team_edit: []
      team_view: []
    content_metadata_id: '9'
    team_edit:
    - PIN_Writer
    team_view:
    - PIN_Viewer
  content_metadata_id: '1'
  team_edit: []
  team_view:
  - PIN_Writer
  - PIN_Viewer
# Looker Role
# Opening Session Welcome to the Capturator, this is the Role place
# -----------------------------------------------------



# PERMISSION SETS
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  name: Report Writer
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_without_limit
  - mobile_app_access
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  - send_to_integration
  name: Viewer
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  - send_to_integration
  name: User
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  name: Writer-2
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_with_limit
  - mobile_app_access
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  name: Report Viewer
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - deploy
  - develop
  - download_without_limit
  - explore
  - manage_groups
  - manage_project_models
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_queries
  - see_sql
  - see_user_dashboards
  - see_users
  - send_to_integration
  - use_global_connections
  - use_sql_runner
  name: Developer


# MODEL SETS
- !LookerModelSet
  models:
  - pin_prod_carelogic
  name: PIN
- !LookerModelSet
  models:
  - pin_prod_carelogic
  name: All


# LOOKER ROLES
- !LookerRoles
  permission_set: User
  model_set: All
  teams:
  - User
  name: User
- !LookerRoles
  permission_set: Developer
  model_set: All
  teams: []
  name: Developer
- !LookerRoles
  permission_set: Viewer
  model_set: All
  teams: []
  name: Viewer
- !LookerRoles
  permission_set: Report Viewer
  model_set: PIN
  teams: []
  name: Viewer-PIN
- !LookerRoles
  permission_set: Report Writer
  model_set: PIN
  teams: []
  name: Writer-PIN
- !LookerRoles
  permission_set: Writer-2
  model_set: PIN
  teams: []
  name: Writer-PIN-2


# USER_ATTRIBUTES
- !LookerUserAttribute
  name: allowed_customer_schemas
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: landing_page
  uatype: relative_url
  hidden_value: false
  user_view: 'True'
  user_edit: 'True'
  default_value: /browse
  teams: []
- !LookerUserAttribute
  name: locale
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: en
  teams: []
- !LookerUserAttribute
  name: looker_internal_email_domain_allowlist
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: number_format
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: 1,234.56
  teams: []
- !LookerUserAttribute
  name: signed_in_org
  uatype: number
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: staff_id
  uatype: number
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
