

# LookData
- !LookObject
  legacy_folder_id: '8'
  look_id: '51'
  title: Test Look
  query_obj:
    model: njstres_prod_carelogic
    view: admissions
    fields:
    - admissions.admission_organization_name
    - admissions.first_admission_date
    - admissions.first_intake_call_date
    - admissions.count_intake
    pivots:
    fill_fields:
    filters:
      client_program.client_program_begin_year: '2022'
    filter_expression:
    sorts: []
    limit: '500'
    column_limit:
    total:
    row_total:
    subtotals:
    vis_config:
      show_view_names: false
      show_row_numbers: true
      transpose: false
      truncate_text: true
      hide_totals: false
      hide_row_totals: false
      size_to_fit: true
      table_theme: white
      limit_displayed_rows: false
      enable_conditional_formatting: false
      header_text_alignment: left
      header_font_size: 12
      rows_font_size: 12
      conditional_formatting_include_totals: false
      conditional_formatting_include_nulls: false
      type: looker_grid
      defaults_version: 1
    filter_config:
      client_program.client_program_begin_year:
      - type: year
        values:
        - constant: '2022'
          unit: yr
        - {}
        id: 1
        error: false
    visible_ui_sections:
    dynamic_fields:
    query_timezone:
  description: ''
  scheduled_plans: []
- !LookObject
  legacy_folder_id: '8'
  look_id: '52'
  title: Bar Chart for Medications Count per Entry Method over Time
  query_obj:
    model: njstres_prod_carelogic
    view: medications
    fields:
    - medications.medications_count
    - medications.medication_begin_month_num
    - medications.entry_method
    pivots:
    - medications.entry_method
    fill_fields:
    - medications.medication_begin_month_num
    filters:
      medications.medication_begin_year: 1 years
    filter_expression:
    sorts:
    - medications.entry_method
    - medications.medications_count desc 0
    limit: '500'
    column_limit:
    total:
    row_total:
    subtotals:
    vis_config:
      x_axis_gridlines: false
      y_axis_gridlines: true
      show_view_names: false
      show_y_axis_labels: true
      show_y_axis_ticks: true
      y_axis_tick_density: default
      y_axis_tick_density_custom: 5
      show_x_axis_label: true
      show_x_axis_ticks: true
      y_axis_scale_mode: linear
      x_axis_reversed: false
      y_axis_reversed: false
      plot_size_by_field: false
      trellis: ''
      stacking: ''
      limit_displayed_rows: false
      legend_position: center
      point_style: none
      show_value_labels: false
      label_density: 25
      x_axis_scale: auto
      y_axis_combined: true
      show_null_points: true
      interpolation: linear
      type: looker_line
      defaults_version: 1
    filter_config:
      medications.medication_begin_year:
      - type: past
        values:
        - constant: '1'
          unit: yr
        - {}
        id: 0
    visible_ui_sections:
    dynamic_fields:
    query_timezone:
  description: ''
  scheduled_plans: []
- !LookObject
  legacy_folder_id: '8'
  look_id: '53'
  title: Top 10 Measures Most Assessed
  query_obj:
    model: njstres_prod_carelogic
    view: impact
    fields:
    - dim_measure.measure
    - document.count_of_documents
    pivots:
    fill_fields:
    filters:
      document.service_year: 1 years
    filter_expression:
    sorts:
    - document.count_of_documents desc 0
    limit: '500'
    column_limit:
    total:
    row_total:
    subtotals:
    vis_config:
      x_axis_gridlines: false
      y_axis_gridlines: true
      show_view_names: false
      show_y_axis_labels: true
      show_y_axis_ticks: true
      y_axis_tick_density: default
      y_axis_tick_density_custom: 5
      show_x_axis_label: true
      show_x_axis_ticks: true
      y_axis_scale_mode: linear
      x_axis_reversed: false
      y_axis_reversed: false
      plot_size_by_field: false
      trellis: ''
      stacking: ''
      limit_displayed_rows: false
      legend_position: center
      point_style: none
      show_value_labels: false
      label_density: 25
      x_axis_scale: auto
      y_axis_combined: true
      ordering: none
      show_null_labels: false
      show_totals_labels: false
      show_silhouette: false
      totals_color: '#808080'
      type: looker_bar
      defaults_version: 1
      series_types: {}
    filter_config:
      document.service_year:
      - type: past
        values:
        - constant: '1'
          unit: yr
        - {}
        id: 0
    visible_ui_sections:
    dynamic_fields:
    query_timezone:
  description: ''
  scheduled_plans: []
- !LookObject
  legacy_folder_id: '8'
  look_id: '54'
  title: Orders Count per Order Type over Time
  query_obj:
    model: njstres_prod_carelogic
    view: orders
    fields:
    - orders.order_effective_month_num
    - orders.orders_count
    - orders.order_type
    pivots:
    - orders.order_type
    fill_fields:
    - orders.order_effective_month_num
    filters:
      orders.order_effective_year: 1 years
    filter_expression:
    sorts:
    - orders.order_type
    - orders.orders_count desc 0
    limit: '500'
    column_limit:
    total:
    row_total:
    subtotals:
    vis_config:
      show_view_names: false
      show_row_numbers: true
      transpose: false
      truncate_text: true
      hide_totals: false
      hide_row_totals: false
      size_to_fit: true
      table_theme: white
      limit_displayed_rows: false
      enable_conditional_formatting: false
      header_text_alignment: left
      header_font_size: 12
      rows_font_size: 12
      conditional_formatting_include_totals: false
      conditional_formatting_include_nulls: false
      type: looker_grid
      defaults_version: 1
    filter_config:
      orders.order_effective_year:
      - type: past
        values:
        - constant: '1'
          unit: yr
        - {}
        id: 0
    visible_ui_sections:
    dynamic_fields:
    query_timezone:
  description: ''
  scheduled_plans: []
- !LookObject
  legacy_folder_id: '8'
  look_id: '55'
  title: Medications Count per Entry Method over Time
  query_obj:
    model: njstres_prod_carelogic
    view: medications
    fields:
    - medications.medications_count
    - medications.entry_method
    - medications.medication_begin_month_num
    pivots:
    - medications.entry_method
    fill_fields:
    - medications.medication_begin_month_num
    filters:
      medications.medication_begin_year: 1 years
    filter_expression:
    sorts:
    - medications.entry_method
    - medications.medications_count desc 0
    limit: '500'
    column_limit:
    total:
    row_total:
    subtotals:
    vis_config:
      x_axis_gridlines: false
      y_axis_gridlines: true
      show_view_names: false
      show_y_axis_labels: true
      show_y_axis_ticks: true
      y_axis_tick_density: default
      y_axis_tick_density_custom: 5
      show_x_axis_label: true
      show_x_axis_ticks: true
      y_axis_scale_mode: linear
      x_axis_reversed: false
      y_axis_reversed: false
      plot_size_by_field: false
      trellis: ''
      stacking: ''
      limit_displayed_rows: false
      legend_position: center
      point_style: none
      show_value_labels: false
      label_density: 25
      x_axis_scale: auto
      y_axis_combined: true
      show_null_points: true
      interpolation: linear
      type: looker_line
      defaults_version: 1
    filter_config:
      medications.medication_begin_year:
      - type: past
        values:
        - constant: '1'
          unit: yr
        - {}
        id: 0
    visible_ui_sections:
    dynamic_fields:
    query_timezone:
  description: ''
  scheduled_plans: []


# Dashboard Content
- !DashboardObject
  legacy_folder_id:
    folder_id: '8'
    slug: GHwRKofzQr5uKB5wiursMO
  lookml: "---\n- dashboard: test_dashboard\n  title: Test Dashboard\n  layout: newspaper\n\
    \  preferred_viewer: dashboards-next\n  description: ''\n  preferred_slug: GHwRKofzQr5uKB5wiursMO\n\
    \  elements:\n  - title: Test Dashboard\n    name: Test Dashboard\n    model:
    njstres_prod_carelogic\n    explore: admissions\n    type: table\n    fields:
    [admissions.intake_status, admissions.count_intake]\n    filters: {}\n    sorts:
    [admissions.count_intake desc 0]\n    limit: 500\n    listen:\n      Intake Call
    Year: admissions.intake_call_year\n    row: 0\n    col: 0\n    width: 10\n   \
    \ height: 6\n  - title: New Tile\n    name: New Tile\n    model: njstres_prod_carelogic\n\
    \    explore: admissions\n    type: looker_grid\n    fields: [admissions.admission_organization_name,
    admissions.first_admission_date,\n      admissions.first_intake_call_date, admissions.count_intake]\n\
    \    filters:\n      client_program.client_program_begin_year: '2022'\n    sorts:
    [admissions.first_admission_date desc 0]\n    limit: 500\n    show_view_names:
    false\n    show_row_numbers: true\n    transpose: false\n    truncate_text: true\n\
    \    hide_totals: false\n    hide_row_totals: false\n    size_to_fit: true\n \
    \   table_theme: white\n    limit_displayed_rows: false\n    enable_conditional_formatting:
    false\n    header_text_alignment: left\n    header_font_size: 12\n    rows_font_size:
    12\n    conditional_formatting_include_totals: false\n    conditional_formatting_include_nulls:
    false\n    defaults_version: 1\n    listen:\n      Intake Call Year: admissions.intake_call_year\n\
    \    row: 0\n    col: 11\n    width: 13\n    height: 6\n  filters:\n  - name:
    Intake Call Year\n    title: Intake Call Year\n    type: field_filter\n    default_value:
    '2022'\n    allow_multiple_values: true\n    required: false\n    ui_config:\n\
    \      type: advanced\n      display: popover\n    model: njstres_prod_carelogic\n\
    \    explore: admissions\n    listens_to_filters: []\n    field: admissions.intake_call_year\n"
  dashboard_id: '3'
  dashboard_slug: GHwRKofzQr5uKB5wiursMO
  dashboard_element_alert_counts:
  - 0
  - 0
  scheduled_plans: []
  alerts: []
- !DashboardObject
  legacy_folder_id:
    folder_id: '8'
    slug: Gz75d3wXtqK0L8Hi6o25gM
  lookml: "---\n- dashboard: medications_count_per_entry_method_over_time\n  title:
    Medications Count per Entry Method over Time\n  layout: newspaper\n  preferred_viewer:
    dashboards-next\n  preferred_slug: Gz75d3wXtqK0L8Hi6o25gM\n  elements:\n  - title:
    Medications Count per Entry Method over Time\n    name: Medications Count per
    Entry Method over Time\n    model: njstres_prod_carelogic\n    explore: medications\n\
    \    type: looker_line\n    fields: [medications.medications_count, medications.entry_method,
    medications.medication_begin_month_num]\n    pivots: [medications.entry_method]\n\
    \    fill_fields: [medications.medication_begin_month_num]\n    filters: {}\n\
    \    sorts: [medications.entry_method, medications.medications_count desc 0]\n\
    \    limit: 500\n    x_axis_gridlines: false\n    y_axis_gridlines: true\n   \
    \ show_view_names: false\n    show_y_axis_labels: true\n    show_y_axis_ticks:
    true\n    y_axis_tick_density: default\n    y_axis_tick_density_custom: 5\n  \
    \  show_x_axis_label: true\n    show_x_axis_ticks: true\n    y_axis_scale_mode:
    linear\n    x_axis_reversed: false\n    y_axis_reversed: false\n    plot_size_by_field:
    false\n    trellis: ''\n    stacking: ''\n    limit_displayed_rows: false\n  \
    \  legend_position: center\n    point_style: none\n    show_value_labels: false\n\
    \    label_density: 25\n    x_axis_scale: auto\n    y_axis_combined: true\n  \
    \  show_null_points: true\n    interpolation: linear\n    defaults_version: 1\n\
    \    listen:\n      Medication Begin Year: medications.medication_begin_year\n\
    \    row: 0\n    col: 0\n    width: 24\n    height: 12\n  filters:\n  - name:
    Medication Begin Year\n    title: Medication Begin Year\n    type: field_filter\n\
    \    default_value: 1 years\n    allow_multiple_values: true\n    required: false\n\
    \    ui_config:\n      type: advanced\n      display: popover\n    model: njstres_prod_carelogic\n\
    \    explore: medications\n    listens_to_filters: []\n    field: medications.medication_begin_year\n"
  dashboard_id: '4'
  dashboard_slug: Gz75d3wXtqK0L8Hi6o25gM
  dashboard_element_alert_counts:
  - 0
  scheduled_plans: []
  alerts: []
- !DashboardObject
  legacy_folder_id:
    folder_id: '8'
    slug: b4I77mV3aHWV8zJWxySi4y
  lookml: "---\n- dashboard: cf_test\n  title: CF Test\n  layout: newspaper\n  preferred_viewer:
    dashboards-next\n  preferred_slug: b4I77mV3aHWV8zJWxySi4y\n  elements:\n  - title:
    CF Test\n    name: CF Test\n    model: njstres_prod_carelogic\n    explore: treatment_plan_plus_forms\n\
    \    type: looker_grid\n    fields: [PresentingProblemandRe1_1477]\n    filters:
    {}\n    dynamic_fields:\n    - category: dimension\n      expression: \"${cf_base.f1}\"\
    \n      dimension: PresentingProblemandRe1_1477\n      label: Presenting Problem
    and Reason  1 1477\n      _kind_hint: dimension\n      _type_hint: string\n  \
    \  - category: dimension\n      expression: \"${cf_base.f2}\"\n      dimension:
    PresentingProblemState2_1477\n      label: 'Presenting Problem: Stated in  2 1477'\n\
    \      _kind_hint: dimension\n      _type_hint: string\n    - category: dimension\n\
    \      expression: \"${cf_base.f3}\"\n      dimension: FamilySupportPersonPre3_1477\n\
    \      label: Family / Support Person Presen 3 1477\n      _kind_hint: dimension\n\
    \      _type_hint: string\n    - category: dimension\n      expression: \"${cf_base.f4}\"\
    \n      dimension: PresentingProblemState4_1477\n      label: 'Presenting Problem:
    Stated in  4 1477'\n      _kind_hint: dimension\n      _type_hint: string\n  \
    \  - category: dimension\n      expression: \"${cf_base.f5}\"\n      dimension:
    HistoryofPresentIllnes5_1477\n      label: 'History of Present Illness: 5 1477'\n\
    \      _kind_hint: dimension\n      _type_hint: string\n    - category: dimension\n\
    \      expression: \"${cf_base.f6}\"\n      dimension: DoestheClienthaveanyim6_1477\n\
    \      label: Does the Client have any immed 6 1477\n      _kind_hint: dimension\n\
    \      _type_hint: string\n    - category: dimension\n      expression: \"${cf_base.f7}\"\
    \n      dimension: Pleasedescribeclientsi7_1477\n      label: Please describe
    client's immed 7 1477\n      _kind_hint: dimension\n      _type_hint: string\n\
    \    - category: dimension\n      expression: \"${cf_base.f8}\"\n      dimension:
    Checkallthatapply9_1477\n      label: 'Check all that apply: 9 1477'\n      _kind_hint:
    dimension\n      _type_hint: string\n    - category: dimension\n      expression:
    \"${cf_base.f9}\"\n      dimension: Explain10_1477\n      label: 'Explain: 10
    1477'\n      _kind_hint: dimension\n      _type_hint: string\n    - category:
    dimension\n      expression: \"${cf_base.f10}\"\n      dimension: Checkallthatapply12_1477\n\
    \      label: 'Check all that apply: 12 1477'\n      _kind_hint: dimension\n \
    \     _type_hint: string\n    - category: dimension\n      expression: \"${cf_base.f11}\"\
    \n      dimension: Explain13_1477\n      label: 'Explain: 13 1477'\n      _kind_hint:
    dimension\n      _type_hint: string\n    - category: dimension\n      expression:
    \"${cf_base.f12}\"\n      dimension: Checkallthatapply15_1477\n      label: 'Check
    all that apply: 15 1477'\n      _kind_hint: dimension\n      _type_hint: string\n\
    \    - category: dimension\n      expression: \"${cf_base.f13}\"\n      dimension:
    Explain16_1477\n      label: 'Explain: 16 1477'\n      _kind_hint: dimension\n\
    \      _type_hint: string\n    - category: dimension\n      expression: \"${cf_base.f14}\"\
    \n      dimension: Checkallthatapply18_1477\n      label: 'Check all that apply:
    18 1477'\n      _kind_hint: dimension\n      _type_hint: string\n    - category:
    dimension\n      expression: \"${cf_base.f15}\"\n      dimension: Explain19_1477\n\
    \      label: 'Explain: 19 1477'\n      _kind_hint: dimension\n      _type_hint:
    string\n    - category: dimension\n      expression: \"${cf_base.f16}\"\n    \
    \  dimension: Describeareasofweaknes21_1477\n      label: Describe areas of weakness
    and 21 1477\n      _kind_hint: dimension\n      _type_hint: string\n    - category:
    dimension\n      expression: \"${cf_base.f17}\"\n      dimension: Whatarethecausesandcon22_1477\n\
    \      label: What are the causes and contri 22 1477\n      _kind_hint: dimension\n\
    \      _type_hint: string\n    - category: dimension\n      expression: \"${cf_base.f18}\"\
    \n      dimension: Whatliferoleswouldthec23_1477\n      label: What life roles
    would the clie 23 1477\n      _kind_hint: dimension\n      _type_hint: string\n\
    \    - category: dimension\n      expression: \"${cf_base.f19}\"\n      dimension:
    Identifycurrentbarrier24_1477\n      label: Identify current barriers to a 24
    1477\n      _kind_hint: dimension\n      _type_hint: string\n    show_view_names:
    false\n    show_row_numbers: true\n    transpose: false\n    truncate_text: true\n\
    \    hide_totals: false\n    hide_row_totals: false\n    size_to_fit: true\n \
    \   table_theme: white\n    limit_displayed_rows: false\n    enable_conditional_formatting:
    false\n    header_text_alignment: left\n    header_font_size: 12\n    rows_font_size:
    12\n    conditional_formatting_include_totals: false\n    conditional_formatting_include_nulls:
    false\n    defaults_version: 1\n    listen:\n      Form ID: cf_base.form_id\n\
    \      Field Name: cf_base.field_name\n    row: 0\n    col: 0\n    width: 24\n\
    \    height: 12\n  filters:\n  - name: Field Name\n    title: Field Name\n   \
    \ type: field_filter\n    default_value: '\"PresentingProblemandRe1_1477,PresentingProblemState2_1477,FamilySupportPersonPre3_1477,PresentingProblemState4_1477,HistoryofPresentIllnes5_1477,DoestheClienthaveanyim6_1477,Pleasedescribeclientsi7_1477,Checkallthatapply9_1477,Explain10_1477,Checkallthatapply12_1477,Explain13_1477,Checkallthatapply15_1477,Explain16_1477,Checkallthatapply18_1477,Explain19_1477,Describeareasofweaknes21_1477,Whatarethecausesandcon22_1477,Whatliferoleswouldthec23_1477,Identifycurrentbarrier24_1477\"\
    '\n    allow_multiple_values: true\n    required: false\n    ui_config:\n    \
    \  type: advanced\n      display: popover\n    model: njstres_prod_carelogic\n\
    \    explore: treatment_plan_plus_forms\n    listens_to_filters: []\n    field:
    cf_base.field_name\n  - name: Form ID\n    title: Form ID\n    type: field_filter\n\
    \    default_value: '1477'\n    allow_multiple_values: true\n    required: false\n\
    \    ui_config:\n      type: advanced\n      display: popover\n    model: njstres_prod_carelogic\n\
    \    explore: treatment_plan_plus_forms\n    listens_to_filters: []\n    field:
    cf_base.form_id\n"
  dashboard_id: '5'
  dashboard_slug: b4I77mV3aHWV8zJWxySi4y
  dashboard_element_alert_counts:
  - 0
  scheduled_plans: []
  alerts: []
