# FOLDER_PERMISSIONS
# Opening Session Welcome to the Capturator, this is the Folder place
# -----------------------------------------------------

- !LookerFolder
  parent_id:
  id: '1'
  name: Shared
  subfolder:
  - !LookerFolder
    parent_id: '1'
    id: '8'
    name: NJSTRES
    subfolder:
    - !LookerFolder
      parent_id: '8'
      id: '62'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '155'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '61'
      name: Utilization
      subfolder: []
      content_metadata_id: '154'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '60'
      name: Supervisory
      subfolder: []
      content_metadata_id: '153'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '59'
      name: System Admin
      subfolder: []
      content_metadata_id: '152'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '58'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '151'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '57'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '150'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '56'
      name: Outcomes
      subfolder: []
      content_metadata_id: '149'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '55'
      name: Operations
      subfolder: []
      content_metadata_id: '148'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '54'
      name: External/Grants
      subfolder: []
      content_metadata_id: '147'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '53'
      name: Executive
      subfolder: []
      content_metadata_id: '146'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '52'
      name: Clinical
      subfolder: []
      content_metadata_id: '145'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '51'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '144'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '50'
      name: Administrative
      subfolder: []
      content_metadata_id: '143'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '49'
      name: In Progress
      subfolder: []
      content_metadata_id: '142'
      team_edit: []
      team_view: []
    content_metadata_id: '9'
    team_edit:
    - NJSTRES_Writer
    team_view:
    - NJSTRES_Viewer
  content_metadata_id: '1'
  team_edit: []
  team_view:
  - NJSTRES_Writer
  - NJSTRES_Viewer
# Looker Role
# Opening Session Welcome to the Capturator, this is the Role place
# -----------------------------------------------------



# PERMISSION SETS
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  name: Writer-2
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  - send_to_integration
  name: User
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - deploy
  - develop
  - download_without_limit
  - explore
  - manage_groups
  - manage_project_models
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_queries
  - see_sql
  - see_user_dashboards
  - see_users
  - send_to_integration
  - use_global_connections
  - use_sql_runner
  name: Developer
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_without_limit
  - mobile_app_access
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  - send_to_integration
  name: Viewer
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  name: Report Writer
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_with_limit
  - mobile_app_access
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  name: Report Viewer


# MODEL SETS
- !LookerModelSet
  models:
  - njstres_prod_carelogic
  name: All
- !LookerModelSet
  models:
  - njstres_prod_carelogic
  name: NJSTRES


# LOOKER ROLES
- !LookerRoles
  permission_set: User
  model_set: All
  teams:
  - User
  name: User
- !LookerRoles
  permission_set: Developer
  model_set: All
  teams: []
  name: Developer
- !LookerRoles
  permission_set: Viewer
  model_set: All
  teams: []
  name: Viewer
- !LookerRoles
  permission_set: Report Viewer
  model_set: NJSTRES
  teams: []
  name: Viewer-NJSTRES
- !LookerRoles
  permission_set: Report Writer
  model_set: NJSTRES
  teams: []
  name: Writer-NJSTRES
- !LookerRoles
  permission_set: Writer-2
  model_set: NJSTRES
  teams: []
  name: Writer-NJSTRES-2


# USER_ATTRIBUTES
- !LookerUserAttribute
  name: allowed_customer_schemas
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: landing_page
  uatype: relative_url
  hidden_value: false
  user_view: 'True'
  user_edit: 'True'
  default_value: /browse
  teams: []
- !LookerUserAttribute
  name: locale
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: en
  teams: []
- !LookerUserAttribute
  name: looker_internal_email_domain_allowlist
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: number_format
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: 1,234.56
  teams: []
- !LookerUserAttribute
  name: signed_in_org
  uatype: number
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: staff_id
  uatype: number
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
