# FOLDER_PERMISSIONS
# Opening Session Welcome to the Capturator, this is the Folder place
# -----------------------------------------------------

- !LookerFolder
  parent_id:
  id: '1'
  name: Shared
  subfolder:
  - !LookerFolder
    parent_id: '1'
    id: '10'
    name: TRLGY
    subfolder:
    - !LookerFolder
      parent_id: '10'
      id: '134'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '231'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '133'
      name: Utilization
      subfolder: []
      content_metadata_id: '230'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '132'
      name: Supervisory
      subfolder: []
      content_metadata_id: '229'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '131'
      name: System Admin
      subfolder: []
      content_metadata_id: '228'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '130'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '227'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '129'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '226'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '128'
      name: Outcomes
      subfolder: []
      content_metadata_id: '225'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '127'
      name: Operations
      subfolder: []
      content_metadata_id: '224'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '126'
      name: External/Grants
      subfolder: []
      content_metadata_id: '223'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '125'
      name: Executive
      subfolder: []
      content_metadata_id: '222'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '124'
      name: Clinical
      subfolder: []
      content_metadata_id: '221'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '123'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '220'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '122'
      name: Administrative
      subfolder: []
      content_metadata_id: '219'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '121'
      name: In Progress
      subfolder: []
      content_metadata_id: '218'
      team_edit: []
      team_view: []
    content_metadata_id: '11'
    team_edit:
    - TRLGY_Writer
    team_view:
    - TRLGY_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '9'
    name: DEMO15
    subfolder:
    - !LookerFolder
      parent_id: '9'
      id: '148'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '245'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '147'
      name: Utilization
      subfolder: []
      content_metadata_id: '244'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '146'
      name: Supervisory
      subfolder: []
      content_metadata_id: '243'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '145'
      name: System Admin
      subfolder: []
      content_metadata_id: '242'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '144'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '241'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '143'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '240'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '142'
      name: Outcomes
      subfolder: []
      content_metadata_id: '239'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '141'
      name: Operations
      subfolder: []
      content_metadata_id: '238'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '140'
      name: External/Grants
      subfolder: []
      content_metadata_id: '237'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '139'
      name: Executive
      subfolder: []
      content_metadata_id: '236'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '138'
      name: Clinical
      subfolder: []
      content_metadata_id: '235'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '137'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '234'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '136'
      name: Administrative
      subfolder: []
      content_metadata_id: '233'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '135'
      name: In Progress
      subfolder: []
      content_metadata_id: '232'
      team_edit: []
      team_view: []
    content_metadata_id: '10'
    team_edit:
    - DEMO15_Writer
    team_view:
    - DEMO15_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '8'
    name: MALCFTD
    subfolder:
    - !LookerFolder
      parent_id: '8'
      id: '120'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '217'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '119'
      name: Utilization
      subfolder: []
      content_metadata_id: '216'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '118'
      name: Supervisory
      subfolder: []
      content_metadata_id: '215'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '117'
      name: System Admin
      subfolder: []
      content_metadata_id: '214'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '116'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '213'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '115'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '212'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '114'
      name: Outcomes
      subfolder: []
      content_metadata_id: '211'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '113'
      name: Operations
      subfolder: []
      content_metadata_id: '210'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '112'
      name: External/Grants
      subfolder: []
      content_metadata_id: '209'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '111'
      name: Executive
      subfolder: []
      content_metadata_id: '208'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '110'
      name: Clinical
      subfolder: []
      content_metadata_id: '207'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '109'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '206'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '108'
      name: Administrative
      subfolder: []
      content_metadata_id: '205'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '107'
      name: In Progress
      subfolder: []
      content_metadata_id: '204'
      team_edit: []
      team_view: []
    content_metadata_id: '9'
    team_edit:
    - MALCFTD_Writer
    team_view:
    - MALCFTD_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '7'
    name: ALHIGHS
    subfolder:
    - !LookerFolder
      parent_id: '7'
      id: '106'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '203'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '105'
      name: Utilization
      subfolder: []
      content_metadata_id: '202'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '104'
      name: Supervisory
      subfolder: []
      content_metadata_id: '201'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '103'
      name: System Admin
      subfolder: []
      content_metadata_id: '200'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '102'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '199'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '101'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '198'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '100'
      name: Outcomes
      subfolder: []
      content_metadata_id: '197'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '99'
      name: Operations
      subfolder: []
      content_metadata_id: '196'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '98'
      name: External/Grants
      subfolder: []
      content_metadata_id: '195'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '97'
      name: Executive
      subfolder: []
      content_metadata_id: '194'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '96'
      name: Clinical
      subfolder: []
      content_metadata_id: '193'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '95'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '192'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '94'
      name: Administrative
      subfolder: []
      content_metadata_id: '191'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '93'
      name: In Progress
      subfolder: []
      content_metadata_id: '190'
      team_edit: []
      team_view: []
    content_metadata_id: '8'
    team_edit:
    - ALHIGHS_Writer
    team_view:
    - ALHIGHS_Viewer
  content_metadata_id: '1'
  team_edit: []
  team_view:
  - ALHIGHS_Viewer
  - ALHIGHS_Writer
  - MALCFTD_Viewer
  - MALCFTD_Writer
  - DEMO15_Viewer
  - DEMO15_Writer
  - TRLGY_Viewer
  - TRLGY_Writer
# Looker Role
# Opening Session Welcome to the Capturator, this is the Role place
# -----------------------------------------------------



# PERMISSION SETS
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  - send_to_integration
  name: User
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - deploy
  - develop
  - download_without_limit
  - explore
  - manage_project_models
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_pdts
  - see_sql
  - see_user_dashboards
  - send_to_integration
  - use_global_connections
  - use_sql_runner
  name: Developer
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_without_limit
  - mobile_app_access
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  - send_to_integration
  name: Viewer


# MODEL SETS
- !LookerModelSet
  models:
  - malcftd_prod_carelogic
  - trlgy_prod_carelogic
  - alhighs_prod_carelogic
  - demo15_prod_carelogic
  name: All


# LOOKER ROLES
- !LookerRoles
  permission_set: User
  model_set: All
  teams:
  - User
  name: User
- !LookerRoles
  permission_set: Developer
  model_set: All
  teams: []
  name: Developer
- !LookerRoles
  permission_set: Viewer
  model_set: All
  teams: []
  name: Viewer


# USER_ATTRIBUTES
- !LookerUserAttribute
  name: allowed_customer_schemas
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: landing_page
  uatype: relative_url
  hidden_value: false
  user_view: 'True'
  user_edit: 'True'
  default_value: /browse
  teams: []
- !LookerUserAttribute
  name: locale
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: looker_internal_email_domain_allowlist
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: number_format
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: signed_in_org
  uatype: number
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: staff_id
  uatype: number
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
