# FOLDER_PERMISSIONS
# Opening Session Welcome to the Capturator, this is the Folder place
# -----------------------------------------------------

- !LookerFolder
  parent_id:
  id: '1'
  name: Shared
  subfolder:
  - !LookerFolder
    parent_id: '1'
    id: '9'
    name: ILLSS
    subfolder:
    - !LookerFolder
      parent_id: '9'
      id: '43'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '116'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '42'
      name: Utilization
      subfolder: []
      content_metadata_id: '115'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '41'
      name: Supervisory
      subfolder: []
      content_metadata_id: '114'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '40'
      name: System Admin
      subfolder: []
      content_metadata_id: '113'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '39'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '112'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '38'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '111'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '37'
      name: Outcomes
      subfolder: []
      content_metadata_id: '110'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '36'
      name: Operations
      subfolder: []
      content_metadata_id: '109'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '35'
      name: External/Grants
      subfolder: []
      content_metadata_id: '108'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '34'
      name: Executive
      subfolder: []
      content_metadata_id: '107'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '33'
      name: Clinical
      subfolder: []
      content_metadata_id: '106'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '32'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '105'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '31'
      name: Administrative
      subfolder: []
      content_metadata_id: '104'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '30'
      name: In Progress
      subfolder: []
      content_metadata_id: '103'
      team_edit: []
      team_view: []
    content_metadata_id: '10'
    team_edit:
    - ILLSS_Writer
    team_view:
    - ILLSS_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '8'
    name: DEMO1
    subfolder:
    - !LookerFolder
      parent_id: '8'
      id: '57'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '130'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '56'
      name: Utilization
      subfolder: []
      content_metadata_id: '129'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '55'
      name: Supervisory
      subfolder: []
      content_metadata_id: '128'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '54'
      name: System Admin
      subfolder: []
      content_metadata_id: '127'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '53'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '126'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '52'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '125'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '51'
      name: Outcomes
      subfolder: []
      content_metadata_id: '124'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '50'
      name: Operations
      subfolder: []
      content_metadata_id: '123'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '49'
      name: External/Grants
      subfolder: []
      content_metadata_id: '122'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '48'
      name: Executive
      subfolder: []
      content_metadata_id: '121'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '47'
      name: Clinical
      subfolder: []
      content_metadata_id: '120'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '46'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '119'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '45'
      name: Administrative
      subfolder: []
      content_metadata_id: '118'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '44'
      name: In Progress
      subfolder: []
      content_metadata_id: '117'
      team_edit: []
      team_view: []
    content_metadata_id: '9'
    team_edit:
    - DEMO1_Writer
    team_view:
    - DEMO1_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '7'
    name: AUTOMATION
    subfolder:
    - !LookerFolder
      parent_id: '7'
      id: '29'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '102'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '28'
      name: Utilization
      subfolder: []
      content_metadata_id: '101'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '27'
      name: Supervisory
      subfolder: []
      content_metadata_id: '100'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '26'
      name: System Admin
      subfolder: []
      content_metadata_id: '99'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '25'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '98'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '24'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '97'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '23'
      name: Outcomes
      subfolder: []
      content_metadata_id: '96'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '22'
      name: Operations
      subfolder: []
      content_metadata_id: '95'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '21'
      name: External/Grants
      subfolder: []
      content_metadata_id: '94'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '20'
      name: Executive
      subfolder: []
      content_metadata_id: '93'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '19'
      name: Clinical
      subfolder: []
      content_metadata_id: '92'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '18'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '91'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '17'
      name: Administrative
      subfolder: []
      content_metadata_id: '90'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '16'
      name: In Progress
      subfolder: []
      content_metadata_id: '89'
      team_edit: []
      team_view: []
    content_metadata_id: '8'
    team_edit:
    - AUTOMATION_Writer
    team_view:
    - AUTOMATION_Viewer
  content_metadata_id: '1'
  team_edit: []
  team_view:
  - AUTOMATION_Viewer
  - AUTOMATION_Writer
  - DEMO1_Viewer
  - DEMO1_Writer
  - ILLSS_Viewer
  - ILLSS_Writer
# Looker Role
# Opening Session Welcome to the Capturator, this is the Role place
# -----------------------------------------------------



# PERMISSION SETS
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  - send_to_integration
  name: User
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_without_limit
  - mobile_app_access
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  - send_to_integration
  name: Viewer
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - deploy
  - develop
  - download_without_limit
  - explore
  - manage_project_models
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_pdts
  - see_sql
  - see_user_dashboards
  - send_to_integration
  - use_global_connections
  - use_sql_runner
  name: Developer


# MODEL SETS
- !LookerModelSet
  models:
  - illss_prod_carelogic
  - demo1_prod_carelogic
  - automation_prod_carelogic
  name: All


# LOOKER ROLES
- !LookerRoles
  permission_set: User
  model_set: All
  teams:
  - User
  name: User
- !LookerRoles
  permission_set: Developer
  model_set: All
  teams: []
  name: Developer
- !LookerRoles
  permission_set: Viewer
  model_set: All
  teams: []
  name: Viewer


# USER_ATTRIBUTES
- !LookerUserAttribute
  name: allowed_customer_schemas
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: landing_page
  uatype: relative_url
  hidden_value: false
  user_view: 'True'
  user_edit: 'True'
  default_value: /browse
  teams: []
- !LookerUserAttribute
  name: locale
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: looker_internal_email_domain_allowlist
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: number_format
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: signed_in_org
  uatype: number
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: staff_id
  uatype: number
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
