# FOLDER_PERMISSIONS
# Opening Session Welcome to the Capturator, this is the Folder place
# -----------------------------------------------------

- !LookerFolder
  parent_id:
  id: '1'
  name: Shared
  subfolder:
  - !LookerFolder
    parent_id: '1'
    id: '11'
    name: DEMO5
    subfolder:
    - !LookerFolder
      parent_id: '11'
      id: '119'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '246'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '118'
      name: Utilization
      subfolder: []
      content_metadata_id: '245'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '117'
      name: Supervisory
      subfolder: []
      content_metadata_id: '244'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '116'
      name: System Admin
      subfolder: []
      content_metadata_id: '243'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '115'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '242'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '114'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '241'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '113'
      name: Outcomes
      subfolder: []
      content_metadata_id: '240'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '112'
      name: Operations
      subfolder: []
      content_metadata_id: '239'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '111'
      name: External/Grants
      subfolder: []
      content_metadata_id: '238'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '110'
      name: Executive
      subfolder: []
      content_metadata_id: '237'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '109'
      name: Clinical
      subfolder: []
      content_metadata_id: '236'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '108'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '235'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '107'
      name: Administrative
      subfolder: []
      content_metadata_id: '234'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '106'
      name: In Progress
      subfolder: []
      content_metadata_id: '233'
      team_edit: []
      team_view: []
    content_metadata_id: '12'
    team_edit:
    - DEMO5_Writer
    team_view:
    - DEMO5_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '10'
    name: MOSBH
    subfolder:
    - !LookerFolder
      parent_id: '10'
      id: '133'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '260'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '132'
      name: Utilization
      subfolder: []
      content_metadata_id: '259'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '131'
      name: Supervisory
      subfolder: []
      content_metadata_id: '258'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '130'
      name: System Admin
      subfolder: []
      content_metadata_id: '257'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '129'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '256'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '128'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '255'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '127'
      name: Outcomes
      subfolder: []
      content_metadata_id: '254'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '126'
      name: Operations
      subfolder: []
      content_metadata_id: '253'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '125'
      name: External/Grants
      subfolder: []
      content_metadata_id: '252'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '124'
      name: Executive
      subfolder: []
      content_metadata_id: '251'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '123'
      name: Clinical
      subfolder: []
      content_metadata_id: '250'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '122'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '249'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '121'
      name: Administrative
      subfolder: []
      content_metadata_id: '248'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '120'
      name: In Progress
      subfolder: []
      content_metadata_id: '247'
      team_edit: []
      team_view: []
    content_metadata_id: '11'
    team_edit:
    - MOSBH_Writer
    team_view:
    - MOSBH_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '9'
    name: CTCCFSN
    subfolder:
    - !LookerFolder
      parent_id: '9'
      id: '147'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '274'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '146'
      name: Utilization
      subfolder: []
      content_metadata_id: '273'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '145'
      name: Supervisory
      subfolder: []
      content_metadata_id: '272'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '144'
      name: System Admin
      subfolder: []
      content_metadata_id: '271'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '143'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '270'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '142'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '269'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '141'
      name: Outcomes
      subfolder: []
      content_metadata_id: '268'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '140'
      name: Operations
      subfolder: []
      content_metadata_id: '267'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '139'
      name: External/Grants
      subfolder: []
      content_metadata_id: '266'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '138'
      name: Executive
      subfolder: []
      content_metadata_id: '265'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '137'
      name: Clinical
      subfolder: []
      content_metadata_id: '264'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '136'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '263'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '135'
      name: Administrative
      subfolder: []
      content_metadata_id: '262'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '134'
      name: In Progress
      subfolder: []
      content_metadata_id: '261'
      team_edit: []
      team_view: []
    content_metadata_id: '10'
    team_edit:
    - CTCCFSN_Writer
    team_view:
    - CTCCFSN_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '8'
    name: CTLNVPCR
    subfolder:
    - !LookerFolder
      parent_id: '8'
      id: '105'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '232'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '104'
      name: Utilization
      subfolder: []
      content_metadata_id: '231'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '103'
      name: Supervisory
      subfolder: []
      content_metadata_id: '230'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '102'
      name: System Admin
      subfolder: []
      content_metadata_id: '229'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '101'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '228'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '100'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '227'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '99'
      name: Outcomes
      subfolder: []
      content_metadata_id: '226'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '98'
      name: Operations
      subfolder: []
      content_metadata_id: '225'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '97'
      name: External/Grants
      subfolder: []
      content_metadata_id: '224'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '96'
      name: Executive
      subfolder: []
      content_metadata_id: '223'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '95'
      name: Clinical
      subfolder: []
      content_metadata_id: '222'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '94'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '221'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '93'
      name: Administrative
      subfolder: []
      content_metadata_id: '220'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '92'
      name: In Progress
      subfolder: []
      content_metadata_id: '219'
      team_edit: []
      team_view: []
    content_metadata_id: '9'
    team_edit:
    - CTLNVPCR_Writer
    team_view:
    - CTLNVPCR_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '7'
    name: MOARTHURCTR
    subfolder:
    - !LookerFolder
      parent_id: '7'
      id: '91'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '218'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '90'
      name: Utilization
      subfolder: []
      content_metadata_id: '217'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '89'
      name: Supervisory
      subfolder: []
      content_metadata_id: '216'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '88'
      name: System Admin
      subfolder: []
      content_metadata_id: '215'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '87'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '214'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '86'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '213'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '85'
      name: Outcomes
      subfolder: []
      content_metadata_id: '212'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '84'
      name: Operations
      subfolder: []
      content_metadata_id: '211'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '83'
      name: External/Grants
      subfolder: []
      content_metadata_id: '210'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '82'
      name: Executive
      subfolder: []
      content_metadata_id: '209'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '81'
      name: Clinical
      subfolder: []
      content_metadata_id: '208'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '80'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '207'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '79'
      name: Administrative
      subfolder: []
      content_metadata_id: '206'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '78'
      name: In Progress
      subfolder: []
      content_metadata_id: '205'
      team_edit: []
      team_view: []
    content_metadata_id: '8'
    team_edit:
    - MOARTHURCTR_Writer
    team_view:
    - MOARTHURCTR_Viewer
  content_metadata_id: '1'
  team_edit: []
  team_view:
  - MOARTHURCTR_Viewer
  - MOARTHURCTR_Writer
  - CTLNVPCR_Viewer
  - CTLNVPCR_Writer
  - CTCCFSN_Viewer
  - CTCCFSN_Writer
  - MOSBH_Viewer
  - MOSBH_Writer
  - DEMO5_Viewer
  - DEMO5_Writer
# Looker Role
# Opening Session Welcome to the Capturator, this is the Role place
# -----------------------------------------------------



# PERMISSION SETS
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  - send_to_integration
  name: User
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_without_limit
  - mobile_app_access
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  - send_to_integration
  name: Viewer
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - deploy
  - develop
  - download_without_limit
  - explore
  - manage_project_models
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_pdts
  - see_sql
  - see_user_dashboards
  - send_to_integration
  - use_global_connections
  - use_sql_runner
  name: Developer


# MODEL SETS
- !LookerModelSet
  models:
  - mosbh_prod_carelogic
  - ctccfsn_prod_carelogic
  - demo5_prod_carelogic
  - moarthurctr_prod_carelogic
  - ctlnvpcr_prod_carelogic
  name: All


# LOOKER ROLES
- !LookerRoles
  permission_set: User
  model_set: All
  teams:
  - User
  name: User
- !LookerRoles
  permission_set: Developer
  model_set: All
  teams: []
  name: Developer
- !LookerRoles
  permission_set: Viewer
  model_set: All
  teams: []
  name: Viewer


# USER_ATTRIBUTES
- !LookerUserAttribute
  name: allowed_customer_schemas
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: landing_page
  uatype: relative_url
  hidden_value: false
  user_view: 'True'
  user_edit: 'True'
  default_value: /browse
  teams: []
- !LookerUserAttribute
  name: locale
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: looker_internal_email_domain_allowlist
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: number_format
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: signed_in_org
  uatype: number
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: staff_id
  uatype: number
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
