# FOLDER_PERMISSIONS
# Opening Session Welcome to the Capturator, this is the Folder place
# -----------------------------------------------------

- !LookerFolder
  parent_id:
  id: '1'
  name: Shared
  subfolder:
  - !LookerFolder
    parent_id: '1'
    id: '9'
    name: DEMO13
    subfolder:
    - !LookerFolder
      parent_id: '9'
      id: '99'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '172'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '98'
      name: Utilization
      subfolder: []
      content_metadata_id: '171'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '97'
      name: Supervisory
      subfolder: []
      content_metadata_id: '170'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '96'
      name: System Admin
      subfolder: []
      content_metadata_id: '169'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '95'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '168'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '94'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '167'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '93'
      name: Outcomes
      subfolder: []
      content_metadata_id: '166'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '92'
      name: Operations
      subfolder: []
      content_metadata_id: '165'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '91'
      name: External/Grants
      subfolder: []
      content_metadata_id: '164'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '90'
      name: Executive
      subfolder: []
      content_metadata_id: '163'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '89'
      name: Clinical
      subfolder: []
      content_metadata_id: '162'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '88'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '161'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '87'
      name: Administrative
      subfolder: []
      content_metadata_id: '160'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '86'
      name: In Progress
      subfolder: []
      content_metadata_id: '159'
      team_edit: []
      team_view: []
    content_metadata_id: '10'
    team_edit:
    - DEMO13_Writer
    team_view:
    - DEMO13_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '8'
    name: WACRMHS
    subfolder:
    - !LookerFolder
      parent_id: '8'
      id: '85'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '158'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '84'
      name: Utilization
      subfolder: []
      content_metadata_id: '157'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '83'
      name: Supervisory
      subfolder: []
      content_metadata_id: '156'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '82'
      name: System Admin
      subfolder: []
      content_metadata_id: '155'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '81'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '154'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '80'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '153'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '79'
      name: Outcomes
      subfolder: []
      content_metadata_id: '152'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '78'
      name: Operations
      subfolder: []
      content_metadata_id: '151'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '77'
      name: External/Grants
      subfolder: []
      content_metadata_id: '150'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '76'
      name: Executive
      subfolder: []
      content_metadata_id: '149'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '75'
      name: Clinical
      subfolder: []
      content_metadata_id: '148'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '74'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '147'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '73'
      name: Administrative
      subfolder: []
      content_metadata_id: '146'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '72'
      name: In Progress
      subfolder: []
      content_metadata_id: '145'
      team_edit: []
      team_view: []
    content_metadata_id: '9'
    team_edit:
    - WACRMHS_Writer
    team_view:
    - WACRMHS_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '7'
    name: AKJUYSI
    subfolder:
    - !LookerFolder
      parent_id: '7'
      id: '71'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '144'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '70'
      name: Utilization
      subfolder: []
      content_metadata_id: '143'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '69'
      name: Supervisory
      subfolder: []
      content_metadata_id: '142'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '68'
      name: System Admin
      subfolder: []
      content_metadata_id: '141'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '67'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '140'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '66'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '139'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '65'
      name: Outcomes
      subfolder: []
      content_metadata_id: '138'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '64'
      name: Operations
      subfolder: []
      content_metadata_id: '137'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '63'
      name: External/Grants
      subfolder: []
      content_metadata_id: '136'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '62'
      name: Executive
      subfolder: []
      content_metadata_id: '135'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '61'
      name: Clinical
      subfolder: []
      content_metadata_id: '134'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '60'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '133'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '59'
      name: Administrative
      subfolder: []
      content_metadata_id: '132'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '58'
      name: In Progress
      subfolder: []
      content_metadata_id: '131'
      team_edit: []
      team_view: []
    content_metadata_id: '8'
    team_edit:
    - AKJUYSI_Writer
    team_view:
    - AKJUYSI_Viewer
  content_metadata_id: '1'
  team_edit: []
  team_view:
  - AKJUYSI_Viewer
  - AKJUYSI_Writer
  - WACRMHS_Viewer
  - WACRMHS_Writer
  - DEMO13_Viewer
  - DEMO13_Writer
# Looker Role
# Opening Session Welcome to the Capturator, this is the Role place
# -----------------------------------------------------



# PERMISSION SETS
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  - send_to_integration
  name: User
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_without_limit
  - mobile_app_access
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  - send_to_integration
  name: Viewer
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - deploy
  - develop
  - download_without_limit
  - explore
  - manage_project_models
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_pdts
  - see_sql
  - see_user_dashboards
  - send_to_integration
  - use_global_connections
  - use_sql_runner
  name: Developer


# MODEL SETS
- !LookerModelSet
  models:
  - akjuysi_prod_carelogic
  - wacrmhs_prod_carelogic
  - demo13_prod_carelogic
  name: All


# LOOKER ROLES
- !LookerRoles
  permission_set: User
  model_set: All
  teams:
  - User
  name: User
- !LookerRoles
  permission_set: Developer
  model_set: All
  teams: []
  name: Developer
- !LookerRoles
  permission_set: Viewer
  model_set: All
  teams: []
  name: Viewer


# USER_ATTRIBUTES
- !LookerUserAttribute
  name: allowed_customer_schemas
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: landing_page
  uatype: relative_url
  hidden_value: false
  user_view: 'True'
  user_edit: 'True'
  default_value: /browse
  teams: []
- !LookerUserAttribute
  name: locale
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: looker_internal_email_domain_allowlist
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: number_format
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: signed_in_org
  uatype: number
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: staff_id
  uatype: number
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
