# FOLDER_PERMISSIONS
# Opening Session Welcome to the Capturator, this is the Folder place
# -----------------------------------------------------

- !LookerFolder
  parent_id:
  id: '1'
  name: Shared
  subfolder:
  - !LookerFolder
    parent_id: '1'
    id: '11'
    name: OHNDI
    subfolder:
    - !LookerFolder
      parent_id: '11'
      id: '37'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '169'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '36'
      name: Utilization
      subfolder: []
      content_metadata_id: '168'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '35'
      name: Supervisory
      subfolder: []
      content_metadata_id: '167'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '34'
      name: System Admin
      subfolder: []
      content_metadata_id: '166'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '33'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '165'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '32'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '164'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '31'
      name: Outcomes
      subfolder: []
      content_metadata_id: '163'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '30'
      name: Operations
      subfolder: []
      content_metadata_id: '162'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '29'
      name: External/Grants
      subfolder: []
      content_metadata_id: '161'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '28'
      name: Executive
      subfolder: []
      content_metadata_id: '160'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '27'
      name: Clinical
      subfolder: []
      content_metadata_id: '159'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '26'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '158'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '25'
      name: Administrative
      subfolder: []
      content_metadata_id: '157'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '11'
      id: '24'
      name: In Progress
      subfolder: []
      content_metadata_id: '156'
      team_edit: []
      team_view: []
    content_metadata_id: '12'
    team_edit:
    - OHNDI_Writer
    team_view:
    - OHNDI_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '10'
    name: DEMO7
    subfolder:
    - !LookerFolder
      parent_id: '10'
      id: '51'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '183'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '50'
      name: Utilization
      subfolder: []
      content_metadata_id: '182'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '49'
      name: Supervisory
      subfolder: []
      content_metadata_id: '181'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '48'
      name: System Admin
      subfolder: []
      content_metadata_id: '180'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '47'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '179'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '46'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '178'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '45'
      name: Outcomes
      subfolder: []
      content_metadata_id: '177'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '44'
      name: Operations
      subfolder: []
      content_metadata_id: '176'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '43'
      name: External/Grants
      subfolder: []
      content_metadata_id: '175'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '42'
      name: Executive
      subfolder: []
      content_metadata_id: '174'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '41'
      name: Clinical
      subfolder: []
      content_metadata_id: '173'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '40'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '172'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '39'
      name: Administrative
      subfolder: []
      content_metadata_id: '171'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '10'
      id: '38'
      name: In Progress
      subfolder: []
      content_metadata_id: '170'
      team_edit: []
      team_view: []
    content_metadata_id: '11'
    team_edit:
    - DEMO7_Writer
    team_view:
    - DEMO7_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '9'
    name: CPLSY
    subfolder:
    - !LookerFolder
      parent_id: '9'
      id: '93'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '225'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '92'
      name: Utilization
      subfolder: []
      content_metadata_id: '224'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '91'
      name: Supervisory
      subfolder: []
      content_metadata_id: '223'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '90'
      name: System Admin
      subfolder: []
      content_metadata_id: '222'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '89'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '221'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '88'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '220'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '87'
      name: Outcomes
      subfolder: []
      content_metadata_id: '219'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '86'
      name: Operations
      subfolder: []
      content_metadata_id: '218'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '85'
      name: External/Grants
      subfolder: []
      content_metadata_id: '217'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '84'
      name: Executive
      subfolder: []
      content_metadata_id: '216'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '83'
      name: Clinical
      subfolder: []
      content_metadata_id: '215'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '82'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '214'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '81'
      name: Administrative
      subfolder: []
      content_metadata_id: '213'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '9'
      id: '80'
      name: In Progress
      subfolder: []
      content_metadata_id: '212'
      team_edit: []
      team_view: []
    content_metadata_id: '10'
    team_edit:
    - CPLSY_Writer
    team_view:
    - CPLSY_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '8'
    name: WAACIHS
    subfolder:
    - !LookerFolder
      parent_id: '8'
      id: '79'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '211'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '78'
      name: Utilization
      subfolder: []
      content_metadata_id: '210'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '77'
      name: Supervisory
      subfolder: []
      content_metadata_id: '209'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '76'
      name: System Admin
      subfolder: []
      content_metadata_id: '208'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '75'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '207'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '74'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '206'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '73'
      name: Outcomes
      subfolder: []
      content_metadata_id: '205'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '72'
      name: Operations
      subfolder: []
      content_metadata_id: '204'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '71'
      name: External/Grants
      subfolder: []
      content_metadata_id: '203'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '70'
      name: Executive
      subfolder: []
      content_metadata_id: '202'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '69'
      name: Clinical
      subfolder: []
      content_metadata_id: '201'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '68'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '200'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '67'
      name: Administrative
      subfolder: []
      content_metadata_id: '199'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '66'
      name: In Progress
      subfolder: []
      content_metadata_id: '198'
      team_edit: []
      team_view: []
    content_metadata_id: '9'
    team_edit:
    - WAACIHS_Writer
    team_view:
    - WAACIHS_Viewer
  - !LookerFolder
    parent_id: '1'
    id: '7'
    name: NJJWFCS
    subfolder:
    - !LookerFolder
      parent_id: '7'
      id: '65'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '197'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '64'
      name: Utilization
      subfolder: []
      content_metadata_id: '196'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '63'
      name: Supervisory
      subfolder: []
      content_metadata_id: '195'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '62'
      name: System Admin
      subfolder: []
      content_metadata_id: '194'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '61'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '193'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '60'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '192'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '59'
      name: Outcomes
      subfolder: []
      content_metadata_id: '191'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '58'
      name: Operations
      subfolder: []
      content_metadata_id: '190'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '57'
      name: External/Grants
      subfolder: []
      content_metadata_id: '189'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '56'
      name: Executive
      subfolder: []
      content_metadata_id: '188'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '55'
      name: Clinical
      subfolder: []
      content_metadata_id: '187'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '54'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '186'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '53'
      name: Administrative
      subfolder: []
      content_metadata_id: '185'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '7'
      id: '52'
      name: In Progress
      subfolder: []
      content_metadata_id: '184'
      team_edit: []
      team_view: []
    content_metadata_id: '8'
    team_edit:
    - NJJWFCS_Writer
    team_view:
    - NJJWFCS_Viewer
  content_metadata_id: '1'
  team_edit: []
  team_view:
  - NJJWFCS_Viewer
  - NJJWFCS_Writer
  - WAACIHS_Viewer
  - WAACIHS_Writer
  - CPLSY_Viewer
  - CPLSY_Writer
  - DEMO7_Viewer
  - DEMO7_Writer
  - OHNDI_Viewer
  - OHNDI_Writer
# Looker Role
# Opening Session Welcome to the Capturator, this is the Role place
# -----------------------------------------------------



# PERMISSION SETS
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - deploy
  - develop
  - download_without_limit
  - explore
  - manage_project_models
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_pdts
  - see_sql
  - see_user_dashboards
  - send_to_integration
  - use_global_connections
  - use_sql_runner
  name: Developer
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_without_limit
  - mobile_app_access
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  - send_to_integration
  name: Viewer
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_sql
  - see_user_dashboards
  - send_to_integration
  name: User


# MODEL SETS
- !LookerModelSet
  models:
  - demo7_prod_carelogic
  - cplsy_prod_carelogic
  - njjwfcs_prod_carelogic
  - ohndi_prod_carelogic
  - waacihs_prod_carelogic
  name: All


# LOOKER ROLES
- !LookerRoles
  permission_set: User
  model_set: All
  teams:
  - User
  name: User
- !LookerRoles
  permission_set: Developer
  model_set: All
  teams: []
  name: Developer
- !LookerRoles
  permission_set: Viewer
  model_set: All
  teams: []
  name: Viewer


# USER_ATTRIBUTES
- !LookerUserAttribute
  name: allowed_customer_schemas
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: landing_page
  uatype: relative_url
  hidden_value: false
  user_view: 'True'
  user_edit: 'True'
  default_value: /browse
  teams: []
- !LookerUserAttribute
  name: locale
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: looker_internal_email_domain_allowlist
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: number_format
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: signed_in_org
  uatype: number
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: staff_id
  uatype: number
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
