# FOLDER_PERMISSIONS
# Opening Session Welcome to the Capturator, this is the Folder place
# -----------------------------------------------------

- !LookerFolder
  parent_id:
  id: '1'
  name: Shared
  subfolder:
  - !LookerFolder
    parent_id: '1'
    id: '8'
    name: CAMCC
    subfolder:
    - !LookerFolder
      parent_id: '8'
      id: '102'
      name: General/Miscellaneous
      subfolder: []
      content_metadata_id: '316'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '101'
      name: Utilization
      subfolder: []
      content_metadata_id: '315'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '100'
      name: Supervisory
      subfolder: []
      content_metadata_id: '314'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '99'
      name: System Admin
      subfolder: []
      content_metadata_id: '313'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '98'
      name: Report Writer/Templates
      subfolder: []
      content_metadata_id: '312'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '97'
      name: QA/Compliance
      subfolder: []
      content_metadata_id: '311'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '96'
      name: Outcomes
      subfolder: []
      content_metadata_id: '310'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '95'
      name: Operations
      subfolder: []
      content_metadata_id: '309'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '94'
      name: External/Grants
      subfolder: []
      content_metadata_id: '308'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '93'
      name: Executive
      subfolder: []
      content_metadata_id: '307'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '92'
      name: Clinical
      subfolder: []
      content_metadata_id: '306'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '91'
      name: Billing/AR
      subfolder: []
      content_metadata_id: '305'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '90'
      name: Administrative
      subfolder: []
      content_metadata_id: '304'
      team_edit: []
      team_view: []
    - !LookerFolder
      parent_id: '8'
      id: '89'
      name: In Progress
      subfolder: []
      content_metadata_id: '303'
      team_edit: []
      team_view: []
    content_metadata_id: '9'
    team_edit:
    - CAMCC_Writer
    team_view:
    - CAMCC_Viewer
  content_metadata_id: '1'
  team_edit: []
  team_view:
  - CAMCC_Viewer
  - CAMCC_Writer
# Looker Role
# Opening Session Welcome to the Capturator, this is the Role place
# -----------------------------------------------------



# PERMISSION SETS
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - save_content
  - save_dashboards
  - save_looks
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  - see_users
  - sudo
  name: QSI Support
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - download_without_limit
  - explore
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  name: Report Writer
- !LookerPermissionSet
  permissions:
  - access_data
  - clear_cache_refresh
  - download_with_limit
  - mobile_app_access
  - see_drill_overlay
  - see_lookml_dashboards
  - see_looks
  - see_user_dashboards
  name: Report Viewer
- !LookerPermissionSet
  permissions:
  - access_data
  - can_create_forecast
  - clear_cache_refresh
  - create_custom_fields
  - create_table_calculations
  - deploy
  - develop
  - download_without_limit
  - explore
  - manage_groups
  - manage_project_models
  - manage_spaces
  - mobile_app_access
  - save_content
  - save_dashboards
  - save_looks
  - schedule_look_emails
  - see_drill_overlay
  - see_lookml
  - see_lookml_dashboards
  - see_looks
  - see_queries
  - see_sql
  - see_user_dashboards
  - see_users
  - send_to_integration
  - use_global_connections
  - use_sql_runner
  name: Developer


# MODEL SETS
- !LookerModelSet
  models:
  - camcc_prod_carelogic
  name: CAMCC
- !LookerModelSet
  models:
  - camcc_prod_carelogic
  name: All


# LOOKER ROLES
- !LookerRoles
  permission_set: Developer
  model_set: All
  teams: []
  name: Developer
- !LookerRoles
  permission_set: Report Viewer
  model_set: CAMCC
  teams: []
  name: Viewer-CAMCC
- !LookerRoles
  permission_set: Report Writer
  model_set: CAMCC
  teams: []
  name: Writer-CAMCC
- !LookerRoles
  permission_set: QSI Support
  model_set: CAMCC
  teams: []
  name: Support


# USER_ATTRIBUTES
- !LookerUserAttribute
  name: allowed_customer_schemas
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: landing_page
  uatype: relative_url
  hidden_value: false
  user_view: 'True'
  user_edit: 'True'
  default_value: /browse
  teams: []
- !LookerUserAttribute
  name: locale
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: en
  teams: []
- !LookerUserAttribute
  name: looker_internal_email_domain_allowlist
  uatype: string
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: number_format
  uatype: string
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: 1,234.56
  teams: []
- !LookerUserAttribute
  name: signed_in_org
  uatype: number
  hidden_value: false
  user_view: 'False'
  user_edit: 'False'
  default_value: ''
  teams: []
- !LookerUserAttribute
  name: staff_id
  uatype: number
  hidden_value: false
  user_view: 'True'
  user_edit: 'False'
  default_value: ''
  teams: []
